/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import dao.*;
import static dao.DaoClient.addclient;
import static dao.DaoCommande.f;


import entities.Book;
import entities.Client;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Ajoutercommande extends javax.swing.JFrame {


    StringBuilder sumid = new StringBuilder();
    double sumo = 0.0;
    StringBuilder sx = new StringBuilder();
    


   

    /**
     * Creates new form Ajoutercommande
     */
    public Ajoutercommande() {
        initComponents();
        try {
            show_bookscommand();
        } catch (SQLException ex) {
            Logger.getLogger(Ajoutercommande.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
   


    //Lister les livres 
     public void show_bookscommand() throws SQLException{
        DaoBook d = new DaoBook();
    ArrayList<Book> listbook = d.listbooks();
    DefaultTableModel model = (DefaultTableModel) jTable_display_books.getModel();
    Object [] row = new Object[6];
    for(int i=0;i<listbook.size();i++)
    {
        row[0]=listbook.get(i).getId();
        row[1]=listbook.get(i).getTitle();
        row[2]=listbook.get(i).getPrice();
        row[3]=listbook.get(i).getAuthor();
        row[4]=listbook.get(i).getReleaseDate();
        row[5]=listbook.get(i).getImage();
        model.addRow(row);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_display_books = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adresse = new javax.swing.JTextField();
        nom1 = new javax.swing.JTextField();
        prenom1 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        tel1 = new javax.swing.JTextField();
        addcom1 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        sum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(25, 11, 66));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(25, 11, 66));
        jPanel1.setForeground(new java.awt.Color(25, 11, 66));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD COMMAND");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 340, 40));

        jTable_display_books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TITLE", "PRICE", "AUTHOR", "DATE", "IMG", "S"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_display_books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_display_booksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_display_books);
        if (jTable_display_books.getColumnModel().getColumnCount() > 0) {
            jTable_display_books.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable_display_books.getColumnModel().getColumn(1).setPreferredWidth(25);
            jTable_display_books.getColumnModel().getColumn(2).setPreferredWidth(15);
            jTable_display_books.getColumnModel().getColumn(3).setPreferredWidth(20);
            jTable_display_books.getColumnModel().getColumn(4).setPreferredWidth(25);
            jTable_display_books.getColumnModel().getColumn(5).setPreferredWidth(40);
            jTable_display_books.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 550, 370));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Adresse:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prénom:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Téléphone:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, 30));

        adresse.setOpaque(false);
        jPanel1.add(adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 170, 30));

        nom1.setOpaque(false);
        jPanel1.add(nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 170, 30));

        prenom1.setOpaque(false);
        jPanel1.add(prenom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 170, 30));

        email1.setOpaque(false);
        jPanel1.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 170, 30));

        tel1.setOpaque(false);
        jPanel1.add(tel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 170, 30));

        addcom1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        addcom1.setForeground(new java.awt.Color(25, 11, 66));
        addcom1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/plus_60px.png"))); // NOI18N
        addcom1.setText("Add Command");
        addcom1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        addcom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcom1ActionPerformed(evt);
            }
        });
        jPanel1.add(addcom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 220, 50));

        reset.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(25, 11, 66));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/sync_50px.png"))); // NOI18N
        reset.setText("Reset               ");
        reset.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 220, 50));

        menu.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        menu.setForeground(new java.awt.Color(25, 11, 66));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/previous_60px.png"))); // NOI18N
        menu.setText("PREVIOUS");
        menu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        sum.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        sum.setForeground(new java.awt.Color(25, 11, 66));
        sum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumMouseClicked(evt);
            }
        });
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });
        jPanel1.add(sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 320, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PRICE:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 80, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/close_window_48px.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 894, 511));

        setSize(new java.awt.Dimension(890, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public StringBuilder getmystring() {

        StringBuilder sx = new StringBuilder();
        try {
            DefaultListSelectionModel selectionModel;

            DefaultTableModel model = (DefaultTableModel) jTable_display_books.getModel();

            for (int i = 0; i < model.getRowCount(); i++) {
                {
                    boolean b = Boolean.parseBoolean(model.getValueAt(i, 6).toString());
                    if (b) {
                        sx = sx.append(Integer.parseInt(model.getValueAt(i, 0).toString()));
                        sx.append(",");
                        System.out.println("*******************************************");
                        System.out.println(sx.toString());
                    }
                }

                //sum.setText(model.getValueAt(selectedrow,0).toString());
            }
        } catch (NullPointerException ex) {
            System.out.println(ex);
        } finally {
            System.out.println(sx.toString());
        }

        return sx;
    }

    private void jTable_display_booksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_display_booksMouseClicked
            // TODO add your handling code here:
        

            DefaultTableModel model = (DefaultTableModel) jTable_display_books.getModel();
        try {
            

            for (int i : jTable_display_books.getSelectedRows()) {
                {
                    boolean b = Boolean.parseBoolean(model.getValueAt(i, 6).toString());
                    if (b) {
                        sumo = sumo + Double.parseDouble(model.getValueAt(i, 2).toString());
                        sx = sx.append(Integer.parseInt(model.getValueAt(i, 0).toString()));
                        sx.append(",");
                    }
                }
                sum.setText(Double.toString(sumo));
                sumid = sx;
      //  sumid.setText(sx.toString());
                //sum.setText(model.getValueAt(selectedrow,0).toString());
            }
        } catch (NullPointerException ex) {
            System.out.println(ex);
        } finally {

            System.out.println(sumo);
            System.out.println(sumid);
        }
    }//GEN-LAST:event_jTable_display_booksMouseClicked


    //Ajout client 
    //add a client

    private void addcom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcom1ActionPerformed
        // TODO add your handling code here:
        String nom = nom1.getText();
        String prenom = prenom1.getText();
        String email = email1.getText();
        String tel = tel1.getText();
        String adresse1 = adresse.getText();
        Client c = new Client();
        c.setNom(nom);
        c.setPrenom(prenom);
        c.setEmail(email);
        c.setTel(tel);
        c.setAdresse(adresse1);
        try {
            addclient(c);
        } catch (SQLException ex) {
            Logger.getLogger(Ajoutercommande.class.getName()).log(Level.SEVERE, null, ex);
        }
        String somme = sum.getText();
        try {


            int result = DaoCommande.add(f(sumid));
            if (result == 1) {
                JOptionPane.showMessageDialog(null, "INSERTED SUCCESSFULLY");
                Menu2 m = new Menu2();
                m.setVisible(true);
                setVisible(false);

            } else {
                JOptionPane.showMessageDialog(null, "FAILED TO INSERT");

            }
        } catch (SQLException ex) {
            Logger.getLogger(Ajoutercommande.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_addcom1ActionPerformed


        
    
    

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        nom1.setText("");
        prenom1.setText("");
        email1.setText("");
        tel1.setText("");
        adresse.setText("");
    }//GEN-LAST:event_resetActionPerformed

//redirection

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        Menu2 m = new Menu2();
        m.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_menuActionPerformed

    private void sumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sumMouseClicked

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajoutercommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajoutercommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajoutercommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajoutercommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajoutercommande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcom1;
    private javax.swing.JTextField adresse;
    private javax.swing.JTextField email1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_display_books;
    private javax.swing.JButton menu;
    private javax.swing.JTextField nom1;
    private javax.swing.JTextField prenom1;
    private javax.swing.JButton reset;
    private javax.swing.JTextField sum;
    private javax.swing.JTextField tel1;
    // End of variables declaration//GEN-END:variables
}
